// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Count: typeof import('./src/components/Count/Count.vue')['default']
    Echart: typeof import('./src/components/Echart/src/Echart.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTableV2: typeof import('element-plus/es')['ElTableV2']
    IconAntDesignDashboardFilled: typeof import('~icons/ant-design/dashboard-filled')['default']
    IconEpExpand: typeof import('~icons/ep/expand')['default']
    IconEpFold: typeof import('~icons/ep/fold')['default']
    IconEpPlace: typeof import('~icons/ep/place')['default']
    IconEpPlatform: typeof import('~icons/ep/platform')['default']
    IconIcOutlineEditLocation: typeof import('~icons/ic/outline-edit-location')['default']
    IconIcSharpDiversity1: typeof import('~icons/ic/sharp-diversity1')['default']
    IconMingcuteEbikeFill: typeof import('~icons/mingcute/ebike-fill')['default']
    Map: typeof import('./src/components/Echart/src/map.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VueCountTo: typeof import('./src/components/Count/vue-countTo.vue')['default']
  }
}
