// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElMenuItemGroup: typeof import('element-plus/es')['ElMenuItemGroup']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    IconEntypoLocationPin: typeof import('~icons/entypo/location-pin')['default']
    IconEpFold: typeof import('~icons/ep/fold')['default']
    IconEplatform: typeof import('~icons/ep/latform')['default']
    IconEpLineMdLaptop: typeof import('~icons/ep/line-md-laptop')['default']
    IconEpPlace: typeof import('~icons/ep/place')['default']
    IconEpplatform: typeof import('~icons/ep/platform')['default']
    IconEpPlatform: typeof import('~icons/ep/platform')['default']
    IconMdiLineMdLaptop: typeof import('~icons/mdi/line-md-laptop')['default']
    IconPsDryNormalLowHeat: typeof import('~icons/ps/dry-normal-low-heat')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
